# Generated by Django 4.0.4 on 2022-05-02 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(choices=[('Clothes', 'Clothes'), ('Laptop', 'Laptop')], max_length=20)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('design', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('madeIn', models.CharField(blank=True, max_length=200)),
                ('manufactureDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='clothes_item_img')),
                ('barcode', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.category')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('madeIn', models.CharField(blank=True, max_length=200)),
                ('yearOfManufacture', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200)),
                ('memory', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=200)),
                ('discountPercent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('dateOfBirth', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='user_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noHome', models.IntegerField(null=True)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SizeClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='clothes_item_img')),
                ('barcode', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.category')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.phone')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='clothes_img')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.phone')),
            ],
        ),
        migrations.CreateModel(
            name='ImageClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='clothes_img')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('rate', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('clothesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clothesitem')),
                ('phoneItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.phoneitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('card', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=200)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('information', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Draft', 'Draft')], max_length=20)),
                ('clothesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clothesitem')),
                ('phoneItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.phoneitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
