# Generated by Django 4.0.4 on 2022-05-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_colorphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='clothesItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.clothesitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='phoneItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.phoneitem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Laptop', 'Laptop'), ('Phone', 'Phone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='clothesItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.clothesitem'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phoneItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.phoneitem'),
        ),
    ]
